### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by eccstartup** [Ming-Zhang-XJTU/XJTU-Thesis-Template#1]
声明部分还是用网上给的pdf吧
定理陈述结束不用空心方块比较好
标点符号可以考虑用半角
公式的结尾一般要根据语境给标点的
声明也要页码？
英文目录：Figures,Tables and Equations 应该加空格 Figures, Tables and Equations

就看到这么多，不过，还有符号表之类的东西
PS: 我也不一定对

**Comment by Ming-Zhang-XJTU** [comment]
非常感谢 eccstartup 的建议，具体说明和修改如下：
1，官方2014年模板的声明和论文在一起。
2，定理陈述部分官方模板没有说明，可以根据个人喜好定义。
3，我也比较喜欢半角标点符号，官方模板用的是全角……
4，有些出版机构要求公式结尾部分根据语境添加标点，有些不需要，官方模板没有给标点（模板里的语境貌似也不需要标点，这一点还不确定）。
5，声明部分的目录没有页码，已经改正。
6，英文目录的空格是我漏掉了，已经改正。
