### ISSUE TITLE
一些修改建议

### ISSUE THREAD

**Issue by hqqxyy** [Ming-Zhang-XJTU/XJTU-Thesis-Template#2]
作者您好，

辛苦了，这个模板做的非常好，我是用这个模板写的研究生毕业论文，万分感谢。

下面是我在打印中被指出来的一些需要修改的地方：

1， ABSTRACT 页眉需要大写

2， ABSTRACT 首行不需要缩进  \noindent

3，目录中应该从绪论开始（修改 摘要 和 ABSTRACT， 注释掉\addcontentsline）

4，ABSTRACT 的行间距好像不太对

祝好
qiqi

**Comment by Ming-Zhang-XJTU** [comment]
非常感谢 qiqi 同学的反馈：
1，ABSTRACT 页眉需要大写：已经改正；
2，ABSTRACT 首行不需要缩进 \noindent：检查了一下，之前的模板没有缩进；
3，目录中应该从绪论开始：已经改正；
4，ABSTRACT 的行间距好像不太对：官方模板的中英文摘要的标题和正文没有对齐，这个模板把二者对齐了，行距对照了一下，确实有细微的差别（不过基本一致，修改过了几个值，都没有达到完全一致）。
